// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UniqueHabits.Data;

#nullable disable

namespace UniqueHabits.Data.Migrations
{
    [DbContext(typeof(HabitsContext))]
    [Migration("20231217014607_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UniqueHabits.Domain.Aggregates.Habit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CategoryDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MeasurableResult")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SystemName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Why")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Habits");
                });

            modelBuilder.Entity("UniqueHabits.Domain.Aggregates.Habit", b =>
                {
                    b.OwnsOne("UniqueHabits.Domain.Aggregates.ImplementationDetails", "ImplementationDetails", b1 =>
                        {
                            b1.Property<Guid>("HabitId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("How")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("When")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Where")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("WithWhat")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("WithWhom")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("HabitId");

                            b1.ToTable("Habits");

                            b1.WithOwner()
                                .HasForeignKey("HabitId");
                        });

                    b.Navigation("ImplementationDetails")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
