// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UniqueHabits.Data;

#nullable disable

namespace UniqueHabits.Data.Migrations
{
    [DbContext(typeof(HabitsContext))]
    [Migration("20240222003325_AddHabitReviewFields")]
    partial class AddHabitReviewFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UniqueHabits.Domain.Aggregates.Habit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CategoryDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MeasurableResult")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SystemName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Why")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Habits");

                    b.HasData(
                        new
                        {
                            Id = new Guid("171d31ef-0a27-4fe8-bfd4-bb12083d5ba0"),
                            Category = "Career",
                            CategoryDescription = "",
                            MeasurableResult = "Improve from a 2 to a 5 (on a scale of 1-10) in terms of confidence in my\r\nleadership knowledge.",
                            StartDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SystemName = "Grow my leadership knowledge each week.",
                            Why = "I want to have more career options so I can change people’s lives."
                        });
                });

            modelBuilder.Entity("UniqueHabits.Domain.Aggregates.Habit", b =>
                {
                    b.OwnsMany("UniqueHabits.Domain.Aggregates.Implementation", "Implementations", b1 =>
                        {
                            b1.Property<Guid>("HabitId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTime>("CreatedDate")
                                .HasColumnType("datetime2");

                            b1.Property<string>("CustomizationDescription")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<Guid?>("PreviousImplementationId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Result")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("When")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Where")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("WithWhat")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("WithWhom")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("HabitId", "Id");

                            b1.ToTable("Implementation");

                            b1.WithOwner()
                                .HasForeignKey("HabitId");

                            b1.OwnsMany("UniqueHabits.Domain.Aggregates.ImplementationStep", "Steps", b2 =>
                                {
                                    b2.Property<Guid>("ImplementationHabitId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<Guid>("ImplementationId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<Guid>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<int>("Sequence")
                                        .HasColumnType("int");

                                    b2.Property<string>("Step")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.HasKey("ImplementationHabitId", "ImplementationId", "Id");

                                    b2.ToTable("ImplementationStep");

                                    b2.WithOwner()
                                        .HasForeignKey("ImplementationHabitId", "ImplementationId");

                                    b2.HasData(
                                        new
                                        {
                                            ImplementationHabitId = new Guid("171d31ef-0a27-4fe8-bfd4-bb12083d5ba0"),
                                            ImplementationId = new Guid("0fd52347-6f3c-461f-b05d-57ae63e9a9f4"),
                                            Id = new Guid("20482634-af53-4db0-99d9-cda5a83da543"),
                                            Sequence = 1,
                                            Step = "Play my \"Energy Music\" playlist."
                                        },
                                        new
                                        {
                                            ImplementationHabitId = new Guid("171d31ef-0a27-4fe8-bfd4-bb12083d5ba0"),
                                            ImplementationId = new Guid("0fd52347-6f3c-461f-b05d-57ae63e9a9f4"),
                                            Id = new Guid("1abdf905-808c-4ac7-bdc7-8741694adcb4"),
                                            Sequence = 2,
                                            Step = "Open LinkedIn Learning app on my tablet."
                                        },
                                        new
                                        {
                                            ImplementationHabitId = new Guid("171d31ef-0a27-4fe8-bfd4-bb12083d5ba0"),
                                            ImplementationId = new Guid("0fd52347-6f3c-461f-b05d-57ae63e9a9f4"),
                                            Id = new Guid("c07213c8-c8a6-491e-8ef5-0388cfcc4066"),
                                            Sequence = 3,
                                            Step = "Continue from the last spot I was at when I finished the day before. (If I don’t have a course, do a search for \"Leadership\" and pick the next one on the list that I haven’t taken.)"
                                        },
                                        new
                                        {
                                            ImplementationHabitId = new Guid("171d31ef-0a27-4fe8-bfd4-bb12083d5ba0"),
                                            ImplementationId = new Guid("0fd52347-6f3c-461f-b05d-57ae63e9a9f4"),
                                            Id = new Guid("15c47fda-6c6e-4901-b463-1ab15addac7e"),
                                            Sequence = 4,
                                            Step = "While watching the course, listen for things I can DO that day."
                                        },
                                        new
                                        {
                                            ImplementationHabitId = new Guid("171d31ef-0a27-4fe8-bfd4-bb12083d5ba0"),
                                            ImplementationId = new Guid("0fd52347-6f3c-461f-b05d-57ae63e9a9f4"),
                                            Id = new Guid("e315e429-fbd6-4a9f-9df3-e3e4bfbb584c"),
                                            Sequence = 5,
                                            Step = "Make notes in Evernote, especially on actions I can take."
                                        },
                                        new
                                        {
                                            ImplementationHabitId = new Guid("171d31ef-0a27-4fe8-bfd4-bb12083d5ba0"),
                                            ImplementationId = new Guid("0fd52347-6f3c-461f-b05d-57ae63e9a9f4"),
                                            Id = new Guid("3dba9c2e-218d-4dad-b1f2-264a4cea85b1"),
                                            Sequence = 6,
                                            Step = "Make notes in Evernote, especially on actions I can take."
                                        },
                                        new
                                        {
                                            ImplementationHabitId = new Guid("171d31ef-0a27-4fe8-bfd4-bb12083d5ba0"),
                                            ImplementationId = new Guid("0fd52347-6f3c-461f-b05d-57ae63e9a9f4"),
                                            Id = new Guid("c61bb021-d507-4cdd-bb5a-7cb0b33b7f28"),
                                            Sequence = 7,
                                            Step = "After 20 minutes, stop."
                                        },
                                        new
                                        {
                                            ImplementationHabitId = new Guid("171d31ef-0a27-4fe8-bfd4-bb12083d5ba0"),
                                            ImplementationId = new Guid("0fd52347-6f3c-461f-b05d-57ae63e9a9f4"),
                                            Id = new Guid("a319ba49-3228-4e61-8ea9-5208d616af07"),
                                            Sequence = 8,
                                            Step = "Copy what I wrote and send myself an email."
                                        },
                                        new
                                        {
                                            ImplementationHabitId = new Guid("171d31ef-0a27-4fe8-bfd4-bb12083d5ba0"),
                                            ImplementationId = new Guid("0fd52347-6f3c-461f-b05d-57ae63e9a9f4"),
                                            Id = new Guid("6d07f8b3-81d6-4cf9-83b5-583029d84185"),
                                            Sequence = 9,
                                            Step = "Read the email when starting my work."
                                        });
                                });

                            b1.Navigation("Steps");

                            b1.HasData(
                                new
                                {
                                    HabitId = new Guid("171d31ef-0a27-4fe8-bfd4-bb12083d5ba0"),
                                    Id = new Guid("0fd52347-6f3c-461f-b05d-57ae63e9a9f4"),
                                    CreatedDate = new DateTime(2024, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                                    When = "Tablet, LinkedIn Learning app, Phone with Evernote (for note-taking), Email",
                                    Where = "On my couch",
                                    WithWhat = "Tablet, LinkedIn Learning app, Phone with Evernote (for note-taking), Email",
                                    WithWhom = "Share on LinkedIn one thing I learned today"
                                });
                        });

                    b.Navigation("Implementations");
                });
#pragma warning restore 612, 618
        }
    }
}
