// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UniqueHabits.Data;

#nullable disable

namespace UniqueHabits.Data.Migrations
{
    [DbContext(typeof(HabitsContext))]
    partial class HabitsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UniqueHabits.Domain.Aggregates.Habit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CategoryDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MeasurableResult")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SystemName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Why")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Habits");

                    b.HasData(
                        new
                        {
                            Id = new Guid("171d31ef-0a27-4fe8-bfd4-bb12083d5ba0"),
                            Category = "Career",
                            CategoryDescription = "",
                            MeasurableResult = "Improve from a 2 to a 5 (on a scale of 1-10) in terms of confidence in my\r\nleadership knowledge.",
                            StartDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SystemName = "Grow my leadership knowledge each week.",
                            Why = "I want to have more career options so I can change people’s lives."
                        });
                });

            modelBuilder.Entity("UniqueHabits.Domain.Aggregates.Habit", b =>
                {
                    b.OwnsOne("UniqueHabits.Domain.Aggregates.ImplementationDetails", "ImplementationDetails", b1 =>
                        {
                            b1.Property<Guid>("HabitId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("How")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("When")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Where")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("WithWhat")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("WithWhom")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("HabitId");

                            b1.ToTable("Habits");

                            b1.WithOwner()
                                .HasForeignKey("HabitId");

                            b1.HasData(
                                new
                                {
                                    HabitId = new Guid("171d31ef-0a27-4fe8-bfd4-bb12083d5ba0"),
                                    How = "• Play my “Energy Music” playlist.\r\n• Open LinkedIn Learning app on my tablet.\r\n• Continue from the last spot I was at when I finished the day before. (If I don’t\r\nhave a course, do a search for “Leadership” and pick the next one on the list that I\r\nhaven’t taken.)\r\n• While watching the course, listen for things I can DO that day.\r\n• Make notes in Evernote, especially on actions I can take.\r\n• After 20 minutes, stop.\r\n• Then take 5 minutes to post on LinkedIn what I learned.\r\n• Copy what I wrote and send myself an email.\r\n• Read the email when starting my work.",
                                    When = "Tablet, LinkedIn Learning app, Phone with Evernote (for note-taking), Email",
                                    Where = "On my couch",
                                    WithWhat = "Tablet, LinkedIn Learning app, Phone with Evernote (for note-taking), Email",
                                    WithWhom = "Share on LinkedIn one thing I learned today"
                                });
                        });

                    b.Navigation("ImplementationDetails")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
